export const HOME = '/'
// export const MYACCOUNT = '/my-account'
// export const BLOG = '/blog'
export const CONTACT = '/contact'
export const DASHBOARD = '/dashboard'
export const MYPROFILE = '/myprofile'
export const MYLOCATIONS = '/mylocations'
export const ABOUTME = '/aboutme'
export const MYLESSONS = '/mylessons'
export const EDUCATIONS = '/educations'
export const EXPERIENCE = '/experience'
export const SKILLSINTEREST = '/skills&interest'
export const GALLERY = '/gallery'
export const MESSAGES = '/messages'
export const FEEDBACK = '/feedback'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const REGISTER = '/register'
export const EMAILVERIFICATION = '/emailverify'
export const THANKYOU = '/thankyou'
export const SUBSCRIPTION = '/subscription'
export const PAYMENTDETAILS = '/paymentdetails'
export const INVOICE = '/invoice'
export const UPDATEPASSWORD = '/updatepassword'
export const DISABLEACCOUNT = '/disablemyacccount'

// Proper zunpakaloudela(admin) Routes
export const ADMINDASHBOARD = '/zunpakaloudela/dashboard'
export const SALES = '/zunpakaloudela/sales'
export const CUSTOMER = '/zunpakaloudela/customer'
export const PACKAGES = '/zunpakaloudela/packages'
export const APPROVALS = '/zunpakaloudela/approvals'
export const CATEGORIES = '/zunpakaloudela/categories'
export const REGISTRATIONS = '/zunpakaloudela/registrations'
// export const SUBCATEGORIES = '/zunpakaloudela/subcategories/:category_id'

export const VERIFYPAYMENT = '/verify-payment'

export const PAGENOTFOUND = '/pagenotfound'

