export const SKILLSINTERESTS_POST_REQUEST = 'SKILLSINTERESTS_POST_REQUEST'
export const SKILLSINTERESTS_POST_FAILURE = 'SKILLSINTERESTS_POST_FAILURE'
export const SKILLSINTERESTS_POST_SUCCESS = 'SKILLSINTERESTS_POST_SUCCESS'
