export const SOCIALMEDIA_POST_REQUEST = 'SOCIALMEDIA_POST_REQUEST'
export const SOCIALMEDIA_POST_FAILURE = 'SOCIALMEDIA_POST_FAILURE'
export const SOCIALMEDIA_POST_SUCCESS = 'SOCIALMEDIA_POST_SUCCESS'
