export const POST_SUBSCRIPTION_REQUEST = 'POST_SUBSCRIPTION_REQUEST'
export const POST_SUBSCRIPTION_FAILURE = 'POST_SUBSCRIPTION_FAILURE'
export const POST_SUBSCRIPTION_SUCCESS = 'POST_SUBSCRIPTION_SUCCESS'
