export const POST_USER_REQUEST = 'POST_USER_REQUEST'
export const POST_USER_FAILURE = 'POST_USER_FAILURE'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'

export const POST_ABOUTME_REQUEST = 'POST_ABOUTME_REQUEST'
export const POST_ABOUTME_SUCCESS = 'POST_ABOUTME_SUCCESS'
export const POST_ABOUTME_FAILURE = 'POST_ABOUTME_FAILURE'

export const POST_PROFILEPICTURE_REQUEST = 'POST_PROFILEPICTURE_REQUEST'
export const POST_PROFILEPICTURE_FAILURE = 'POST_PROFILEPICTURE_FAILURE'
export const POST_PROFILEPICTURE_SUCCESS = 'POST_PROFILEPICTURE_SUCCESS'
// export const GET_PROFILEPICTURE_REQUEST = 'GET_PROFILEPICTURE_REQUEST'
// export const GET_PROFILEPICTURE_FAILURE = 'GET_PROFILEPICTURE_FAILURE'
// export const GET_PROFILEPICTURE_SUCCESS = 'GET_PROFILEPICTURE_SUCCESS'
